### ISSUE TITLE
Admin page is blank with PHP error

### ISSUE THREAD

**Issue by kmlucy** [splitbrain/dokuwiki#1935]
I just updated from Elenor of Tsort and when I try to load my admin page, I just get the header and a blank page. In my error logs, I get the following:
```
2017/04/01 23:23:32 [error] 16#16: *287 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method admin_plugin_styling::getMenuIcon() in /var/www/inc/Ui/Admin.php:154
Stack trace:
#0 /var/www/inc/Ui/Admin.php(23): dokuwiki\Ui\Admin->getPluginList()
#1 /var/www/inc/template.php(266): dokuwiki\Ui\Admin->show()
#2 /var/www/inc/template.php(164): tpl_admin()
#3 /var/www/inc/events.php(111): tpl_content_core('admin')
#4 /var/www/inc/events.php(238): Doku_Event->trigger('tpl_content_" while reading upstream, client: 172.17.0.1, server: , request: "GET /doku.php?id=start&do=admin HTTP/1.0", upstream: "fastcgi://unix:/var/run/php-fpm7.sock:", host: "*************", referrer: "https://*************************"
2017/04/01 23:23:32 [error] 16#16: *287 FastCGI sent in stderr: "cor...', true)
#5 /var/www/inc/template.php(83): trigger_event('TPL_ACT_RENDER', 'admin', 'tpl_content_cor...')
#6 /var/www/lib/tpl/bootstrap3/main.php(86): tpl_content(false)
#7 /var/www/inc/actions.php(199): include('/var/www/lib/tp...')
#8 /var/www/doku.php(124): act_dispatch()
#9 {main}
  thrown in /var/www/inc/Ui/Admin.php on line 154" while reading upstream, client: 172.17.0.1, server: , request: "GET /doku.php?id=start&do=admin HTTP/1.0", upstream: "fastcgi://unix:/var/run/php-fpm7.sock:", host: "********************", referrer: "https://**********************"
```

I have tried restarting DokuWiki, clearing my cache and cookies, etc. with no success.

**Comment by splitbrain** [comment]
Some of your files seem not to have been correctly updated. Try downloading and upgrading again.

See also https://forum.dokuwiki.org/thread/14594
