### ISSUE TITLE
Plain Text Password in log files

### ISSUE THREAD

**Issue by michaelpollmann** [splitbrain/dokuwiki#2125]
Plain text password appears in apache ssl_error log file, for instance when login fails due to missing permissions for /dev/urandom directory.
See also for an example log:
https://github.com/splitbrain/dokuwiki/issues/1892#issuecomment-296790436
(that issue asks for better info for the failed login, this issue is about the plain text passwords)

Please ensure that whatever function prints the plain text passwords in log files isn't called, here or elsewhere.

**Comment by splitbrain** [comment]
Which auth backend are you using?

**Comment by andreasferber** [comment]
The printing in question is done by the xdebug PHP extension due to an unhandled exception, not by Dokuwiki itself. If you have a debugging PHP setup, it's normal that sensitive data might end up in the log. Just disable xdebug. If your host doesn't allow that, first of all you should look for another host, since xdebug might present all sorts of issues on a production systems, but in the meantime you can add a file `conf/local.protected.php` containing:
```php
<?php
xdebug_disable();
```

**Comment by Thoronador** [comment]
@andreasferber 
Unfortunately, the xdebug extension to PHP might not be the reason that the credentials show up in the server's error logs. I am experiencing the same issue on my server and the xdebug extension to PHP is definitely not installed on that server. Trying to calling `xdebug_disable()` in a PHP script anyway (just to be sure) yields the error message

    PHP Fatal error:  Call to undefined function xdebug_disable() in /var/www/[...]/test.php on line 2

xdebug is not installed, otherwise the function should not be undefined. So it cannot be xdebug's fault in the first place.

**Comment by splitbrain** [comment]
The example log linked above shows a stack trace with collected parameters. As @andreasferber mentioned, this is usually only available with xdebug. The plain auth mechanism should never log passwords, but other backends may. So I ask again: what backend are you using?

**Comment by michaelpollmann** [comment]
@splitbrain 
in the configuration, authtype is set to authplain. The drop-down is grayed out saying that no other option is possible.

**Comment by michaelpollmann** [comment]
In our own log, it appears more like this:
`[Mon Sep 11 17:21:53 2017] [error] [client 128.12.137.165] PHP Fatal error:  Uncaught exception 'Exception' with message 'There is no suitable CSPRNG installed on your system' in ...wiki/vendor/paragonie/random_compat/lib/random.php:203
Stack trace:
#0 ...wiki/inc/auth.php(333): random_bytes(16)
#1 ...wiki/inc/auth.php(360): auth_randombytes(16)
#2 ...wiki/inc/auth.php(229): auth_encrypt('...', '0564de946378e12...')
#3 ...wiki/inc/auth.php(178): auth_login('<user-name>', '<password>', false, false)
#4 ...wiki/inc/events.php(111): auth_login_wrapper(Array)
#5 ...wiki/inc/events.php(238): Doku_Event->trigger('auth_login_wrap...', true)
#6 ...wiki/inc/auth.php(109): trigger_event('AUTH_LOGIN_CHEC...', Array, 'auth_login_wrap...')
#7 ...wiki/inc/init.php(223): auth_setup()
#8 ...wiki/doku.php(34): require_once('...')
#9 {main}
  thrown in ...wiki/vendor/paragonie/random_compat/lib/random.php on line 203, referer: .../doku.php?id=start&do=login&sectok=`

**Comment by splitbrain** [comment]
It seems that newer PHP versions do create detailed stacktraces by default which includes passed parameters. There's nothing we can do about that AFAIK.

The proper way to "fix" this is to register a global error handler and do the error logging ourselves. This might be a good idea in general, but will require some more complex refactoring.
