### ISSUE TITLE
XML-RPC uncaught ArgumentCountError

### ISSUE THREAD

**Issue by phy25** [splitbrain/dokuwiki#2545]
```
POST http://localhost/dokuwiki/lib/exe/xmlrpc.php
content-type: application/xml

  <?xml version="1.0"?>
    <methodCall>
      <methodName>dokuwiki.search</methodName>
    </methodCall>
```

Expected (example only):

```
<?xml version="1.0" ?>
<methodResponse>
<fault>
<value>
<struct>
<member>
<name>faultCode</name>
<value>
<int>-32602</int>
</value>
 </member>
<member>
<name>faultString</name>
<value>
<string>Wrong number of parameters or invalid method parameters.</string>
</value>
 </member>
 </struct>
</value>
</fault>
</methodResponse>
```

Actual:

```
date: Fri, 19 Oct 2018 18:06:32 GMT
server: Apache/2.4.34 (Win32) OpenSSL/1.1.0i PHP/7.2.10
x-powered-by: PHP/7.2.10
vary: Cookie
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
content-length: 1103
content-type: text/html; charset=UTF-8
<br />
<b>Fatal error</b>:  Uncaught ArgumentCountError: Too few arguments to function RemoteAPICore::search(), 0 passed in \htdocs\dokuwiki\inc\remote.php on line 179 and exactly 1 expected in \htdocs\dokuwiki\inc\RemoteAPICore.php:336
Stack trace:
#0 \htdocs\dokuwiki\inc\remote.php(179): RemoteAPICore-&gt;search()
#1 \htdocs\dokuwiki\inc\remote.php(96): RemoteAPI-&gt;callCoreMethod('dokuwiki.search', Array)
#2 \htdocs\dokuwiki\lib\exe\xmlrpc.php(33): RemoteAPI-&gt;call('dokuwiki.search', Array)
#3 \htdocs\dokuwiki\inc\IXR_Library.php(424): dokuwiki_xmlrpc_server-&gt;call('dokuwiki.search', NULL)
#4 \htdocs\dokuwiki\inc\IXR_Library.php(400): IXR_Server-&gt;serve('&lt;?xml version=&quot;...')
#5 \htdocs\dokuwiki\lib\exe\xmlrpc.php(23): IXR_Server-&gt;__construct()
#6 \htdocs\dokuwiki\lib\exe\xmlrpc.php(65): dokuwiki_xmlrpc_server-&gt;__construct()
#7 {main}
  thrown in <b>\htdocs\dokuwiki\inc\RemoteAPICore.php</b> on line <b>336</b><br />
```

**Comment by phy25** [comment]
This is because of a PHP 7.1 change: https://www.php.net/manual/en/migration71.incompatible.php#migration71.incompatible.too-few-arguments-exception

Previously `call_user_func_array` will make those missing arguments to NULL. I would like to go through all remote API methods to see if enforcing the argument check is OK, and probably catch ArgumentCountError here: https://github.com/splitbrain/dokuwiki/blob/f17724f821884e579f5b6eb846ed95c7d5b15eeb/inc/Remote/Api.php#L169
