### ISSUE TITLE
Please help me install the translation plugin

### ISSUE THREAD

**Issue by xaozai** [splitbrain/dokuwiki#3083]
What I did:
- Installed dokuwiki (it works fine)
- installed the translation plugin
 - In the file `lib/tpl/dokuwiki/main.php` added:
```
<?php
$translation = &plugin_load('syntax','translation');
echo $translation->_showTranslations();
?>
```
It turned out like this:
```
<?php
/**
 * DokuWiki Default Template 2012
 *
 * @link     http://dokuwiki.org/template
 * @author   Anika Henke <anika@selfthinker.org>
 * @author   Clarence Lee <clarencedglee@gmail.com>
 * @license  GPL 2 (http://www.gnu.org/licenses/gpl.html)
 */

if (!defined('DOKU_INC')) die(); /* must be run from within DokuWiki */

$hasSidebar = page_findnearest($conf['sidebar']);
$showSidebar = $hasSidebar && ($ACT=='show');
?><!DOCTYPE html>
<html lang="<?php echo $conf['lang'] ?>" dir="<?php echo $lang['direction'] ?>" class="no-js">
<head>
    <meta charset="utf-8" />
    <title><?php tpl_pagetitle() ?> [<?php echo strip_tags($conf['title']) ?>]</title>
    <script>(function(H){H.className=H.className.replace(/\bno-js\b/,'js')})(document.documentElement)</script>
    <?php tpl_metaheaders() ?>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <?php echo tpl_favicon(array('favicon', 'mobile')) ?>
    <?php tpl_includeFile('meta.html') ?>
</head>

<body>
    <div id="dokuwiki__site"><div id="dokuwiki__top" class="site <?php echo tpl_classes(); ?> <?php
        echo ($showSidebar) ? 'showSidebar' : ''; ?> <?php echo ($hasSidebar) ? 'hasSidebar' : ''; ?>">

        <?php include('tpl_header.php') ?>
        
        <?php
                $translation = &plugin_load('syntax','translation');
                echo $translation->_showTranslations();
        ?>

        <div class="wrapper group">

        ...
```

Now dokuwiki pages don't display content.

In nginx logs I see the following errors:
```
2020/05/22 14:33:53 [error] 11597#11597: *358 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function _showTranslations() on null in /var/www/dokuwiki/lib/tpl/dokuwiki/main.php:36
Stack trace:
#0 /var/www/dokuwiki/inc/actions.php(27): include()
#1 /var/www/dokuwiki/doku.php(120): act_dispatch()
#2 {main}
  thrown in /var/www//dokuwiki/lib/tpl/dokuwiki/main.php on line 36" while reading upstream, client: 192.168.1.4, server: _, request: "GET /doku.php?id=ru:start HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "192.168.1.2", referrer: "http://192.168.1.2/doku.php?id=ru:start&do=index"
```

How do I install this plugin correctly?

**Comment by phy25** [comment]
This is probably not the right place. Please use forum.dokuwiki.org or https://github.com/splitbrain/dokuwiki-plugin-translation/issues
