### ISSUE TITLE
"✗ Could not find download for info"  on plugin.php extension upgrade

### ISSUE THREAD

**Issue by e1mo** [splitbrain/dokuwiki#3227]
When executing `bin/plugin.php extension upgrade --loglevel debug` it fails and returns:

```
bin/plugin.php extension upgrade --loglevel debug
splitbrain\phpcli\Exception caught in /home/e1mo/tmp/dokuwiki/vendor/splitbrain/php-cli/src/Options.php:231
#0 /home/e1mo/tmp/dokuwiki/vendor/splitbrain/php-cli/src/Options.php(282): splitbrain\phpcli\Options->parseOptions()
#1 /home/e1mo/tmp/dokuwiki/vendor/splitbrain/php-cli/src/CLI.php(159): splitbrain\phpcli\Options->parseOptions()
#2 /home/e1mo/tmp/dokuwiki/vendor/splitbrain/php-cli/src/CLI.php(93): splitbrain\phpcli\CLI->parseOptions()
#3 /home/e1mo/tmp/dokuwiki/bin/plugin.php(41): splitbrain\phpcli\CLI->run()
#4 /home/e1mo/tmp/dokuwiki/vendor/splitbrain/php-cli/src/CLI.php(175): PluginCLI->main()
#5 /home/e1mo/tmp/dokuwiki/vendor/splitbrain/php-cli/src/CLI.php(97): splitbrain\phpcli\CLI->execute()
#6 /home/e1mo/tmp/dokuwiki/bin/plugin.php(103): splitbrain\phpcli\CLI->run()
#7 {main}
☠ No such option 'loglevel'
```

 - Dokuwiki Version: 096f04eff7aad873454dc31dfd0c594ceaa5b3af (latest stable as of today)
 - PHP Version:
```
php --version
PHP 7.4.9 (cli) (built: Aug  5 2020 05:00:11) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies
```
- Operating System: Arch Linux x86_64

**Comment by splitbrain** [comment]
the loglevel option belongs to the main command. Use `./bin/plugin.php --loglevel debug extension upgrade`

**Comment by e1mo** [comment]
Even when running the command you provided, it still fails with return code 1.
```
./bin/plugin.php --loglevel debug extension upgrade
✗ Could not find download for info
```
