### ISSUE TITLE
Unsupported operand types

### ISSUE THREAD

**Issue by splitbrain** [splitbrain/dokuwiki#3339]
I found the following error in our server's error log:

```
PHP message: PHP Fatal error:  Uncaught Error: Unsupported operand types in /var/www/wiki/htdocs/inc/Ui/Revisions.php:224
Stack trace:
#0 /var/www/wiki/htdocs/inc/Ui/Revisions.php(65): dokuwiki\\Ui\\Revisions->getRevisions(0, false)
#1 /var/www/wiki/htdocs/inc/Ui/Revisions.php(46): dokuwiki\\Ui\\Revisions->showMediaRevisions('plugin:translat...')
#2 /var/www/wiki/htdocs/inc/html.php(305): dokuwiki\\Ui\\Revisions->show()
#3 /var/www/wiki/htdocs/inc/media.php(995): html_revisions(0, 'plugin:translat...')
#4 /var/www/wiki/htdocs/inc/template.php(1479): media_tab_history('plugin:translat...', 'plugin')
#5 /var/www/wiki/htdocs/inc/template.php(1776): tpl_mediaFileDetails('plugin:translat...', 0)
#6 /var/www/wiki/htdocs/inc/Action/Media.php(21): tpl_media()
#7 /var/www/wiki/htdocs/inc/template.php(99): dokuwiki\\Action\\Media->tplContent()
#8 [internal function]: tpl_content_core('media')
#9 /var/www/wiki/htdocs/inc/Extension/Event.php(129): call_user_func_array('tpl_content_cor...', Array)
#10 /var/www/wiki/ht...error:  Uncaught Error: Unsupported operand types in /var/www/wiki/htdocs/inc/Ui/Revisions.php:224
```

From the timestamp I figured out it was a request to https://www.dokuwiki.org/tips:farm?do=media&image=plugin%3Atranslation-plugin-2007-10-17.tgz&ns=marketing&tab_details=history&tab_files=files

The problem is in this statement:

```php
                $revisions[] = $changelog->getRevisionInfo($rev) + array(
                        'media' => true,
                        'current' => true,
                );
```

`getRevisionInfo` can return false when no revision is found which will cause the above problem. However I'm not sure what to return in that case. I guess it would make sense to synthesize a proper result from the known data?

@ssahara seems like you touched this code last. Could you have a look?

**Comment by ssahara** [comment]
@splitbrain , please let me see what I can do to solve this issue.
