### ISSUE TITLE
Installer script won't launch on Nginx + PHP 7.4

### ISSUE THREAD

**Issue by danielthegray** [splitbrain/dokuwiki#3483]
I am trying to install Doku wiki on a FreeBSD server. I have installed the `nginx` and `php74` packages, and configured them. phpinfo(); successfully appears in a separate file, so the link between Nginx and PHP-FPM is working well.

If I access the installer script, however, I get the following error in the error.log:
```
2021/04/28 01:05:20 [error] 8913#100099: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error: 
Uncaught Error: Call to undefined function session_name() in 
    /usr/local/www/nginx-dist/html/wiki/inc/init.php:231
Stack trace:
#0 /usr/local/www/nginx-dist/html/wiki/inc/init.php(157): init_session()
#1 /usr/local/www/nginx-dist/html/wiki/install.php(22): require_once('/usr/local/www/...')
#2 {main}
  thrown in /usr/local/www/nginx-dist/html/wiki/inc/init.php on line 231"
  while reading response header from upstream, client: 192.168.178.22, server: localhost,
  request: "GET /wiki/install.php HTTP/1.1",
  upstream: "fastcgi://unix:/var/run/php-fpm.sock:",
  host: "192.168.178.17"
```
I cannot find anything in the wiki or documentation that refers to it. I have checked the php.ini configuration and nothing strange seems to be happening there... but I am still stumped as to why it is unable to find the `session_name()` function. I've tried the -oldstable and -stable packages and both have a very similar result.

Is this a compatibility issue or am I missing some PHP plugin that handles sessions (the documentation of the `session_name()` element doesn't seem to suggest that it comes from an external plugin.

**Comment by phy25** [comment]
First time I am aware that session extension could be turned off. Could you check in your phpinfo whether session is enabled?

**Comment by danielthegray** [comment]
I'm not sure what extension could have been disabled or where to check... here is the "Core" section of the phpinfo, not sure if it's helpful:
![image](https://user-images.githubusercontent.com/7434508/116363189-27bd0780-a803-11eb-908d-d8b895e192f5.png)

or maybe I should just paste the whole thing:
![image](https://user-images.githubusercontent.com/7434508/116363332-4e7b3e00-a803-11eb-8296-ee6c67e94212.png)

**Comment by mprins** [comment]
this might help: https://forum.dokuwiki.org/d/16760-blank-page-error-500-after-upgrade-to-greebo-on-freebsd

**Comment by danielthegray** [comment]
Indeed, that made me notice that there is a `php74-session` package, which I should have looked into myself, apologies! Thanks for the pointer! Now there is a "session" section in the phpinfo() right after "pcre" and "Reflection".

Now there is a permissions error, but this is probably expected and at least it is very clearly indicated!

**Comment by Klap-in** [comment]
We are already checking for the existance of `session_start()` in the installer, but not `session_name`. Is `session_start()` not part of that `php74-session`? Or is `session_name()` called earlier?
 https://github.com/turnermm/dokuwiki/blob/21e0c4ee85c704dc1b2f6ea59a71f1e657863f03/install.php#L586

**Comment by danielthegray** [comment]
The `check_functions` is called much later. The session_name failure happens because of the call in line 22 of the same file:
https://github.com/turnermm/dokuwiki/blob/21e0c4ee85c704dc1b2f6ea59a71f1e657863f03/install.php#L22

which trips the call here:
https://github.com/turnermm/dokuwiki/blob/21e0c4ee85c704dc1b2f6ea59a71f1e657863f03/inc/init.php#L245

**Comment by Ishayahu** [comment]
Maybe it related to that error:
I've updated my system (FreeBSD) and php changed from 7.2 to 7.4. I've installed mod_php74 and now got warning (dokuwiki still working) on top of my page:
`Warning: session_name(): Cannot change session name when session is active in /usr/local/www/dokuwiki/inc/init.php on line 245

Warning: session_set_cookie_params(): Cannot change session cookie parameters when session is active in /usr/local/www/dokuwiki/inc/init.php on line 251`
