### ISSUE TITLE
Error with register mail

### ISSUE THREAD

**Issue by D4di69** [splitbrain/dokuwiki#3644]
My wiki works perfectly themes, extensions, content but when someone tries to register an account get this error:
`Fatal error: Uncaught Error: Class 'EmailAddressValidator' not found in /home/torre502/public_html/chaoswiki/inc/mail.php:89 Stack trace: #0 /home/torre502/public_html/chaoswiki/inc/auth.php(890): mail_isvalid('curiousstr.e.a....') #1 /home/torre502/public_html/chaoswiki/inc/Action/Register.php(35): register() #2 /home/torre502/public_html/chaoswiki/inc/ActionRouter.php(83): dokuwiki\Action\Register->preProcess() #3 /home/torre502/public_html/chaoswiki/inc/ActionRouter.php(48): dokuwiki\ActionRouter->setupAction('register') #4 /home/torre502/public_html/chaoswiki/inc/ActionRouter.php(60): dokuwiki\ActionRouter->__construct() #5 /home/torre502/public_html/chaoswiki/inc/actions.php(16): dokuwiki\ActionRouter::getInstance(true) #6 /home/torre502/public_html/chaoswiki/doku.php(122): act_dispatch() #7 {main} thrown in /home/torre502/public_html/chaoswiki/inc/mail.php on line 89`
I'm actually hosting my wiki on https://torrentdonkey.com/chaoswiki/
Please help me solve this problem.

**Comment by D4di69** [comment]
Sorry, this problem came from corrupted files, i'm closing the issue
