### ISSUE TITLE
"strlen(): Argument #1 ($string) must be of type string, array given" when reconfiguring the Wiki

### ISSUE THREAD

**Issue by sromeroi** [splitbrain/dokuwiki#3737]
I just updated my working Dokuwiki under PHP7 to `Dokuwiki Release 2022-07-31 "Igor"` with PHP 8.1 and I'm having an issue each time I try to alter anything under `?do=admin&page=config`.

When I try to save the configuration (even if I don't change anything) I get this error in data/log/YYYY-MM-DD.log:

```
2022-08-07 16:55:41     /var/www/myweb/public_html/wiki/inc/Utf8/Clean.php(34)  TypeError: strlen(): Argument #1 ($string) must be of type string, array given
  #0 /var/www/myweb/public_html/wiki/inc/Utf8/Clean.php(34): strlen()
  #1 /var/www/myweb/public_html/wiki/inc/common.php(994): dokuwiki\Utf8\Clean::isUtf8()
  #2 /var/www/myweb/public_html/wiki/lib/plugins/config/core/Setting/Setting.php(235): cleanText()
  #3 /var/www/myweb/public_html/wiki/lib/plugins/config/core/Writer.php(49): dokuwiki\plugin\config\core\Setting\Setting->out()
  #4 /var/www/myweb/public_html/wiki/lib/plugins/config/core/Configuration.php(126): dokuwiki\plugin\config\core\Writer->save()
  #5 /var/www/myweb/public_html/wiki/lib/plugins/config/admin.php(54): dokuwiki\plugin\config\core\Configuration->save()
  #6 /var/www/myweb/public_html/wiki/inc/Action/Admin.php(33): admin_plugin_config->handle()
  #7 /var/www/myweb/public_html/wiki/inc/ActionRouter.php(83): dokuwiki\Action\Admin->preProcess()
  #8 /var/www/myweb/public_html/wiki/inc/ActionRouter.php(48): dokuwiki\ActionRouter->setupAction()
  #9 /var/www/myweb/public_html/wiki/inc/ActionRouter.php(60): dokuwiki\ActionRouter->__construct()
  #10 /var/www/myweb/public_html/wiki/inc/actions.php(16): dokuwiki\ActionRouter::getInstance()
  #11 /var/www/myweb/public_html/wiki/doku.php(126): act_dispatch()
  #12 {main}
```

Then, conf/local.php is created as a 0 bytes file (with the right permissions and owner, it is not a permissions problem) and I have to recover it from backup.

I don't see anything strange in the original local.conf file that justifies the error in Clean.php:

```
<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: XXXXXXX
 * Date: Wed, 28 Dec 2016 20:25:31 +0100
 */

$conf['title'] = 'XXXXX.org';
$conf['start'] = 'indice';
$conf['lang'] = 'es';
$conf['template'] = 'dokuwiki';
$conf['sidebar'] = '';
$conf['license'] = '';
$conf['breadcrumbs'] = 4;
$conf['youarehere'] = 1;
$conf['typography'] = '0';
$conf['dformat'] = '%d-%m-%Y %H:%M';
$conf['useheading'] = '1';
$conf['sneaky_index'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'recent,revisions,register,subscribens,unsubscribens,subscribe,unsubscribe,source,export_raw';
$conf['auth_security_timeout'] = 1200;
$conf['htmlok'] = 1;
$conf['target']['media'] = '_blank';
$conf['jpg_quality'] = 85;
$conf['rss_type'] = 'rss2';
$conf['rss_linkto'] = 'page';
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['proxy']['user'] = 'sromero';
$conf['plugin']['googleanalytics']['GAID'] = 'UA-XXXXXX-1';
$conf['plugin']['googleanalytics']['dont_count_admin'] = 1;
$conf['plugin']['googleanalytics']['dont_count_users'] = 1;
$conf['plugin']['authmysql']['TablesToLock'] = array();
$conf['logo'] = '<img src="/wiki/logowiki.png" alt="wiki XXXX" />';

// end auto-generated content
```

Any idea on what's wrong?

Thanks.

**Comment by sromeroi** [comment]
Ok, I narrorred it down to:

`$conf['plugin']['authmysql']['TablesToLock'] = array();' 

I don't know why that setting was autogenerated but removing it fixes the issue.

I've been updating the wiki from ages so maybe this is a reminiscence of older versions.

Anyway, fixed, thanks!
